### ISSUE TITLE
Lot number

### ISSUE THREAD

**Issue by AlexanderDilthey** [nickloman/mockcommunity#2]
Hi Nick,

Do you happen to have the lot number of the ZymoBIOMICS DNA source?

According to https://www.zymoresearch.com/media/amasty/amfile/attach/_D6300_ZymoBIOMICS_Microbial_Community_Standard_v1.1.3.pdf (Appendix  B), the used strains were switched at some point in the product circle...

Cheers,

Alex

**Comment by nickloman** [comment]
Hi Alex

Firstly just want to point you over to https://github.com/LomanLab/mockcommunity as the canonical repo for this dataset (sorry there are multiple forks!).

There's a tad bit of confusion about lot numbers for the even community and as you said there has been some changes in recent times.

To address this and some other issues with species representation from the extraction method used we are currently generating new datasets for MinION and PromethION for both the log and even communities with known log numbers. We anticipate posting them next week, thanks for your patience!

Best
Nick

**Comment by AlexanderDilthey** [comment]
Thank you, Nick!

Cheers,

Alex
